#!/bin/sh
### BEGIN INIT INFO
# Provides:          sanji-controller
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Should-Start:      bootmisc gpsd gpsc
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Controller of Sanji framework
# Description:       start/stop the sanji-controller
### END INIT INFO

SANJI_CONTROLLER=/usr/bin/sanji-controller
SANJI_CONFIG=/etc/sanji-controller.conf
SANJI_OPTIONS=""

case "$1" in
start)
	${SANJI_CONTROLLER} ${SANJI_OPTIONS} -c ${SANJI_CONFIG}
	;;
stop)
	killall ${SANJI_CONTROLLER}
	;;
restart)
	$0 stop
	$0 start
	;;
reload)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
	exit 1;
	;;
esac

exit 0
